version: "3.6"
services:
  next_dev:
    build:
      context: "./"
      dockerfile: Dockerfile.dev
    environment:
      LDAP_URL: ${LDAP_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_JWT_SECRET: ${NEXTAUTH_JWT_SECRET}
    volumes:
      - "./src:/app/src"
    ports:
      - "3000:3000"
    depends_on:
      - ldap
  ldap:
    image: osixia/openldap:stable
    container_name: ldap
    command: --copy-service
    environment:
      LDAP_SSL_HELPER_PREFIX: "ldap"
      LDAP_TLS_VERIFY_CLIENT: "never"
    tty: true
    stdin_open: true
    volumes:
      - ./ldap-server/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    ports:
      - "389:389"
      - "636:636"
    domainname: "ldap.example.org" # important: same as hostname
    hostname: "ldap.example.org"
